before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
    # override $NODE_VERSION
    - CI_COMMIT_MESSAGE="$(git log -1 --pretty=%s)" && if (printf "$CI_COMMIT_MESSAGE" | grep -qE "\bNODE_VERSION="); then nvm install "$(printf "$CI_COMMIT_MESSAGE" | sed -e "s/.*\bNODE_VERSION=//" -e "s/ .*//")" && node --version && npm --version; fi
branches:
    only:
    - /^alpha$/
    - /^beta$/
    - /^benchmark\..*/
    - /^cron$/
    - /^docker\..*/
    - /^master$/
    - /^publish$/
    - /^task$/
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: JuvFx4LL5azFv5FdQ5rleUw4HqMTZwB1y2PcaNAtI2u+l4BFK+0oMiNp14W8CZxDtc7Exibaw4HwrZzwjg+f04CANF/dvguGVdw6BtlpnHi71YdOO+z7Hri6/ARlllugy7+9fLdPGfIQMZqfAVDD4fehTBIvU4G6ovIhaTwAwT5ZeLfxN64skKfI3qx31XLqwGLng1IpFNF4PkjktlTgQG6lgoZtB9O4tlXxn/raldXFjiu8+jy6Pkz6DEyHQhK96KPiECttP/dcmyWE78nABklQSocBBvPoUsr/jSUpxqOHavJScYLkCSdU8SvA3iqrh8gNK076ffVXj1jcdNetvw8XOjxP1usBxQ0ZmoLz7KaVi2RB6beH2I0wuPzF1GJQDUQmsGdCm4zqpLdy+tZV0V6NgiAglxeEG0n+82F2UQ9GuDD2+XkElFiC+ntWp75HYSiH0YDAWuBQfYz/7m/vhtLpvyHHZMNZJspeUwu6PcWsYZgppyMFhFkRZvcI9F0RkkXPE1PrILBw7wG/hFVueU6uZRJZ1h4m1D7P86cIdZ9QnPzMsdeV3VCK/KbuHcha51EweQlVsCc5uDEGJjCTWWYhJ9F3UY3TYUbtdeZbYJFgj/qxLXyzR2zm28rQgqvEgMhXxOSTkUp7xQTOyvvgLfkMw3M43R42z16Fzt4KdLo= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
